variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
  - pages


pages:
  image: alpine
  stage: pages
  script:
  - apk --no-cache add gcc musl-dev py3-pip python3-dev linux-headers
  - apk --no-cache add make
  - python3 -m venv doc && source ./doc/bin/activate
  - python3 -m pip install -r requirements.txt jupyter-book
  - jupyter-book build .
  - mv _build/html ./public
  artifacts:
    paths:
    - public
    expire_in: 30 days
  only:
    - main
